### PR TITLE
alc fix in userspace for latest AppleALC

### PR DESCRIPTION
**Pull request by crazyi**
The fix is from @Sniki

### CODE REVIEW

**Comment by crazyi** [comment]
The fix is from @Sniki

**Comment by i3p9** [comment]
Hey, I was also looking at ALCPlug-Swift and wanted to incorporate it into the EFI. Thanks for doing it. Before I merge, have you tested this yourself? 

After that, I'll change the instructions at [README.md](https://github.com/i3p9/Hackintosh-BigSur-Catalina-OpenCore-Lenovo-T450s-efi/blob/master/Utilities/README.md) in the `alc_fix` section.

**Comment by crazyi** [comment]
> Hey, I was also looking at ALCPlug-Swift and wanted to incorporate it into the EFI. Thanks for doing it. Before I merge, have you tested this yourself?
> 
> After that, I'll change the instructions at [README.md](https://github.com/i3p9/Hackintosh-BigSur-Catalina-OpenCore-Lenovo-T450s-efi/blob/master/Utilities/README.md) in the `alc_fix` section.

Yes, I had already tested on my T450s.

**Comment by i3p9** [comment]
Merged. Thanks so much!

**Pull request merged**
